name: Deploy to GitHub Pages
on:
  push:
    branches:
      - sources
  release:
    types:
      - created
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
        git config --global user.email "herisn23@gmail.com"
        git config --global user.name "Deploybot"
        npm run deploy
