name: Deploy to GitHub Pages
on:
  push:
    branches:
      - sources
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.12.0'
      - name: Deploy on server
        run: |
          git config --global user.email "herisn23@gmail.com"
          git config --global user.name "Deploy Bot"
          npm install
          npm run build
          npm run deploy
